Source-Machine-Ent/Algorithm-class

ningpop/1920.py
closed #165 
- 풀이 일자: 2022.05.26
- 풀이 시간: 15분 18초
- 채점 결과: 시간 초과 -> 정답
- 시간복잡도: O(logN)
- 문제 링크: https://www.acmicpc.net/problem/1920
1. 정렬을 하지 않고 리스트에 원소가 있는지 판단하는 `if ~ in ~` 구문을 이용하여 풀이하였더니 시간초과 처리되었습니다.
2. 이진탐색을 사용하여 풀이하였더니 정답처리 되었습니다.
=> [#165] 1920 수 찾기

keich_park/2504.kt, keich_park/5639.kt
5639 이진 검색 트리
- 풀이 일자: 2022.05.27
- 풀이 시간: 70분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/5639
=> BOJ 5639 kotlin

JOLLA/5639.py
5639 이진 검색 트리
- 풀이 일자: 2022.05.27
- 풀이 시간: 1시간
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/5639
접근 방법에서 꼬여서 정답지를 참고하여 작성하였음
=> Commit: 5639.py

keich_park/11653.kt
11653 소인수분해
- 풀이 일자: 2022.05.28
- 풀이 시간: 15분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/11653
=> BOJ 11653 kotlin

ningpop/5639.py
closed #174 
- 풀이 일자: 2022.05.27
- 풀이 시간: 64분 54초
- 채점 결과: 시간 초과 -> 정답
- 시간복잡도: O(N^2)
- 문제 링크: https://www.acmicpc.net/problem/5639
1. 일반적으로 노드 클래스를 만들고, 전위순회 한 값을 가져와 트리를 만든 후, 후위순회 출력하였으나 시간초과 처리 되었습니다.
2. 배열에 전위순회한대로 저장해서 관리하는 방법을 찾아보고 익힌 후 풀이하였더니 정답처리 되었습니다.
=> [#174] 5639 이진 검색 트리

ningpop/11653.py
closed #179 
- 풀이 일자: 2022.05.31
- 풀이 시간: 5분 23초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://www.acmicpc.net/problem/11653
1. 소인수 분해 과정을 i값을 증가시키며 사용하였고, 정답 처리 되었습니다.
=> [#179] 11653 소인수분해

orlando/5569/test.py
=> BOJ 5569 저장 안해놓고 올려서 다시올리는 pr

keich_park/7579.kt
7579 앱
- 풀이 일자: 2022.06.01
- 풀이 시간: 120분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/7579
=> BOJ 7579 kotlin

JOLLA/7579.py
7579 
- 풀이 일자: 2022.06.01
- 풀이 시간: 
- 채점 결과: 오답
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/{문제번호}
=> Commit: 7579.py

ningpop/1837.py
closed #198 
- 풀이 일자: 2022.06.05
- 풀이 시간: 48분 38초
- 채점 결과: 메모리 초과 -> 시간 초과 -> 정답
- 시간복잡도: O(NloglogN)
- 문제 링크: https://www.acmicpc.net/problem/1837
1. P까지의 모든 소수를 구하고 그 소수들의 조합을 구해 곱한 경우를 골라내었더니 메모리 초과 처리되었습니다.
2. 테스트 케이스로 주어지는 수의 약수는 `[1, p, q, P]`로 될 것을 예상하고, P의 약수를 구한 뒤, 1과 P가 아닌 두 수를 가지고 판별하였더니 시간 초과 처리되었습니다.
3. 새로운 풀이를 발견하였습니다. 판별 조건은 k보다 큰지 작은지 이므로, k까지의 소수를 구한 뒤, 소수들로 P를 나눠보고 나누어 떨어진다면 BAD를 출력하게 하였더니 정답처리 되었습니다.
=> [#198] 1837 암호제작

JOLLA/programmers/printer.py
printer 
- 풀이 일자: 2022.06.06
- 풀이 시간: 1시간
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://programmers.co.kr/learn/courses/30/lessons/42587
=> Commit: printer.py

ningpop/5582.py
closed #210 
- 풀이 일자: 2022.06.10
- 풀이 시간: 32분 34초
- 채점 결과: 시간 초과(Python3) -> 정답(Pypy3)
- 시간복잡도: O(N*M)
- 문제 링크: https://www.acmicpc.net/problem/5582
1. 둘 중 작은 문자열의 길이부터 0까지 줄여나가며 긴 문자열에 있는지 확인하는 방법을 사용하였더니 시간초과 처리 되었습니다.(Python3)
2. DP 풀이를 참고하여 2차원 배열을 생성해 풀이하였더니 시간초과 처리 되었습니다.(Python3)
3. Pypy3로 다시 제출하였더니 정답 처리 되었습니다.
=> [#210] 5582 공통 부분 문자열

ningpop/1759.py
closed #211 
- 풀이 일자: 2022.06.11
- 풀이 시간: 34분 11초
- 채점 결과: 정답
- 시간복잡도: O(N)?
- 문제 링크: https://www.acmicpc.net/problem/1759
모음과 자음이 등장하는 갯수에 대한 경우의 수 조합을 먼저 뽑고 그에 맞춰서 모음/자음을 조합하였고, 그 결과를 정렬해 출력하였더니 정답 처리 되었습니다.
=> [#211] 1759 암호 만들기

JOLLA/programmers/spy.py, JOLLA/programmers/target_number.py
위장
- 풀이 일자: 2022.06.09
- 풀이 시간: 30분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://programmers.co.kr/learn/courses/30/lessons/42578
=> Commit: spy.py

JOLLA/programmers/biggest_num.py
가장 큰 수
- 풀이 일자: 2022.06.09
- 풀이 시간: 40분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://programmers.co.kr/learn/courses/30/lessons/42746
=> Commit: biggest_num.py

JOLLA/programmers/bridge_truck.py, JOLLA/programmers/more_spicy.py
더 맵게
- 풀이 일자: 2022.06.10
- 풀이 시간: 50분
- 채점 결과: 정답
- 시간복잡도: 
- 문제 링크: https://programmers.co.kr/learn/courses/30/lessons/42626
=> Commit: more_spicy.py

orlando/13251/test.py
13251
- 풀이 일자: 2022.06.13
- 풀이 시간: 21분
- 채점 결과: 정답
- 시간복잡도: O(n)
- 문제 링크: https://www.acmicpc.net/problem/13251
=> [2022-06-13] 13251 BOJ

ningpop/13251.py
closed #222
- 풀이 일자: 2022.06.14
- 풀이 시간: 13분 55초
- 채점 결과: 정답
- 시간복잡도: O(N*K)
- 문제 링크: https://www.acmicpc.net/problem/13251
확률을 계산하는 방법을 사용하여 풀이하였고, 정답 처리 되었습니다.
같은 색이 나올 확률은 확률의 곱셈, 그 확률이 다른 색들의 경우의 수를 구하는 것은 확률의 덧셈을 사용하였습니다.
=> [#222] 13251 조약돌 꺼내기

ningpop/9252.py
closed #228 
- 풀이 일자: 2022.06.16
- 풀이 시간: 59분 04초
- 채점 결과: 시간 초과 -> 정답
- 시간복잡도: O(N*M)
- 문제 링크: https://www.acmicpc.net/problem/9252
1. DP테이블을 만들 때, 같은 문자가 나오면 +1 만 하고 다른 문자일때는 0값을 저장하는 형태로 만들고 다시 스캔하는 방식을 사용하였더니 시간초과 처리 되었습니다.
2. 풀이를 확인한 후, DP테이블을 만들 때, 누적된 값이 다 저장되는 방식으로 만들고 나서 스캔하였더니 정답 처리 되었습니다.
=> [#228] 9252 LCS 2

ningpop/1927.py
closed #238 
- 풀이 일자: 2022.06.21
- 풀이 시간: 05분 58초
- 채점 결과: 정답
- 시간복잡도: O(NlogN)
- 문제 링크: https://www.acmicpc.net/problem/1927
파이썬의 heapq 모듈을 사용하여 풀이하였습니다.
=> [#238] 1927 최소 힙

ningpop/15663.py
closed #240 
- 풀이 일자: 2022.06.23
- 풀이 시간: 08분 33초
- 채점 결과: 정답
- 시간복잡도: O(N!)
- 문제 링크: https://www.acmicpc.net/problem/15663
itertools 모듈의 permutations를 사용하여 풀이하였고 정답 처리 되었습니다.
=> [#240] 15663 N과 M (9)

ningpop/1339.py
closed #247 
- 풀이 일자: 2022.06.23
- 풀이 시간: 65분 46초
- 채점 결과: 오답 -> 시간 초과 -> 정답
- 시간복잡도: O(N)
- 문제 링크: https://www.acmicpc.net/problem/1339
1. 단어를 한글자씩 2차원 배열에 저장해두고 자릿수가 가장 큰 글자에 큰 숫자를 매칭하였더니 반례에 걸려 오답 처리 되었습니다.
```
반례: 
10
ABB
BC
BC
BC
BC
BC
BC
BC
BC
BC
출력값: 1771
정답값: 1772
```
2. 숫자가 매칭되는 모든 조합을 구한 뒤에 가장 큰 값으로 갱신시키는 방식으로 풀이하였더니 시간 초과 처리 되었습니다.
3. 풀이를 참고해 단어의 글자가 등장하는 자릿수를 기록해두고 숫자를 곱하는 방식을 사용하였더니 정답 처리 되었습니다.
=> [#247] 1339 단어 수학

ningpop/11279.py
closed #251 
- 풀이 일자: 2022.06.24
- 풀이 시간: 07분 07초
- 채점 결과: 정답
- 시간복잡도: O(N^2logN)
- 문제 링크: https://www.acmicpc.net/problem/11279
Python의 heapq 모듈을 사용하였고, heapq는 최소 힙으로 구현되어 있기에, - 부호를 붙여 바꾸어 풀이하였고 정답 처리 되었습니다.
=> [#251] 11279 최대 힙

ningpop/4375.py
closed #256 
- 풀이 일자: 2022.06.25
- 풀이 시간: 14분 19초
- 채점 결과: 정답
- 시간복잡도: O(loglogN)
- 문제 링크: https://www.acmicpc.net/problem/4375
1씩 붙여가며 나눠보고 나머지가 0인 경우의 숫자를 알아내어 자릿수를 세었고, 정답 처리 되었습니다.
=> [#256] 4375 1

ningpop/11657.py
closed #263 
- 풀이 일자: 2022.06.28
- 풀이 시간: 39분 42초
- 채점 결과: 정답
- 시간복잡도: O(NM)
- 문제 링크: https://www.acmicpc.net/problem/11657
음의 가중치를 처리할 수 있는 벨만포드 알고리즘을 학습한 후에 풀이하였고, 정답 처리 되었습니다.
=> [#263] 11657 타임머신

ningpop/2449.py
#265 
- 풀이 일자: 2022.06.29
- 풀이 시간: 60분 40초
- 채점 결과: 미해결
- 시간복잡도: 
- 문제 링크: https://www.acmicpc.net/problem/2449
풀이를 보았는데도 이해하지 못했습니다. 이후 다시 풀어볼 예정입니다.
=> [#265] 2449 전구 - 미해결

ningpop/15686.py
closed #267 
- 풀이 일자: 2022.06.30
- 풀이 시간: 35분 14초
- 채점 결과: 정답
- 시간복잡도: O(N^3)
- 문제 링크: https://www.acmicpc.net/problem/15686
Python3의 combinations 모듈을 사용하여 치킨집의 조합 경우의 수를 구한 뒤, 조합 중에 가장 작은 치킨거리를 찾아내는 방식으로 풀이하였습니다.
=> [#267] 15686 치킨 배달 - 정답

ningpop/1655.py
closed #270 
- 풀이 일자: 2022.07.01
- 풀이 시간: 68분 40초
- 채점 결과: 시간 초과 -> 오답 -> 정답
- 시간복잡도: O(NlogNlogN)
- 문제 링크: https://www.acmicpc.net/problem/1655
1. 우선순위 큐 하나를 사용하여 매번 push와 pop를 하여 가운데 값을 출력하는 방식을 사용하였으나, 시간 초과 처리 되었습니다.
2. 1번 방식과 동일하나, 가운데 값을 출력할 때, 반복 횟수를 줄여 제출하였으나, 시간 초과 처리 되었습니다.
3. 풀이를 참고하여 우선순위 큐를 2개 사용하여 최대 힙, 최소 힙을 사용하여 풀이하였으나, 조건문 처리에 문제가 있어 오답 처리 되었습니다.
4. 조건문을 수정하여 정답 처리 되었습니다.
=> [#270] 1655 가운데를 말해요 - 정답
